name: CI

# Trigger this workflow on push or pull request
on: [push, pull_request]
jobs:
  build:
     name: Build
     runs-on: [windows-latest]
     steps:
      - uses: actions/checkout@v1
        
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build x64
        run: |
          cd $env:SRC_DIR_PATH
          echo $env:SRC_DIR_PATH
          dir
          msbuild /p:Configuration=Release /p:Platform=x64
          
      - name: Build Win32
        run: |
          cd $env:SRC_DIR_PATH
          msbuild /p:Configuration=Release /p:Platform=x86
      
      
          
